### ISSUE TITLE
MAIN TODO 

### ISSUE THREAD

**Issue by arjunkalburgi** [askalburgi/CMPUT379ASSIGNMENT2#10]
- [x] [Client side write sanitization](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/3) - connectAndTalk.c:75 
- [x] [Server side logic](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/5) - talk.c:63 (results in writing to socket) 
- [x] [Client side read](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/11) - connectAndTalk.c:85
- [x] [Connected message on client](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/2) - 
.
- [x] [Server backend](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/7) 
.
- [ ] Compile and run convoluted bs

**Comment by arjunkalburgi** [comment]
@aseth99 
- [ ] [Server side logic](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/5) - testing
- [x] [Client side read](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/11) - testing 
- [x] [Client side write sanitization](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/3) - testing

**Comment by arjunkalburgi** [comment]
[**Interface**](https://github.com/askalburgi/CMPUT379ASSIGNMENT2/issues/12)

- [x] Client orderly exit on Ctrl+C and "Exit"
- [ ] Client callable as the following command: `wbc379 hostname portnumber [keyfile]`
- [ ] Server callable as the following command: `wbs379 portnumber {-f statefile | -n entries}`
- [ ] Server orderly terminate on SIGTERM message

**Comment by arjunkalburgi** [comment]
### BUGS

- [x] client logic read on connection established - garbage outputs
- [ ] better input 
`scanf("Query (?) or Update (@): ", call); 
scanf("Which entry would you like: ", entry);
`

**Comment by aseth99** [comment]
- [x] need to prepend CMPUT379 Whiteboard Encrypted v0\n to the plaintext of all encrypted entries @12c128/n"....."/n 

- [x] implement flag on entry

- [x] remove all encryption from server

- [ ] write the read for the client

- [ ]
